// nx/apps/reactapp/src/app/app.tsx
import React from 'react';

import './app.scss';

import { BrowserRouter as Router, Route, Link } from 'react-router-dom';

export const App = () => {
  return (
    <Router>
      <div>
        <ul>
          <li>
            <Link to="/">Root</Link>
          </li>
        </ul>
        <header style={{ textAlign: 'center' }}>
          <nx-greeting title={'reactapp!'} />
          <img
            width="450"
            src="https://raw.githubusercontent.com/nrwl/nx/master/nx-logo.png"
          />
        </header>
        <p>
          This is a React app built with <a href="https://nx.dev">Nx</a>.
        </p>
        <p>
          🔎 **Nx is a set of Angular CLI power-ups for modern development.**
        </p>
        <h2>Quick Start & Documentation</h2>
        <ul>
          <li>
            <a href="https://nx.dev/getting-started/what-is-nx">
              30-minute video showing all Nx features
            </a>
          </li>
          <li>
            <a href="https://nx.dev/tutorial/01-create-application">
              Interactive tutorial
            </a>
          </li>
        </ul>
        <Route
          path="/"
          exact
          render={() => <div>This is the root route.</div>}
        />
      </div>
    </Router>
  );
};

export default App;

// nx/apps/angularapp/src/app/app.component.ts
import { Component } from '@angular/core';
import { ToDo } from '@nx/data';
import { ToDoFacade } from './+state/to-do.facade';
import { Observable } from 'rxjs';

@Component({
  selector: 'nx-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.scss']
})
export class AppComponent {
  title = 'angularapp';
  todos: Observable<ToDo[]> = this.toDoFacade.allToDo$;

  constructor(private toDoFacade: ToDoFacade) {
    this.toDoFacade.loadAll();
  }

  addTodo(): void {
    this.toDoFacade.addTodo();
  }
}

<div style="text-align:center">
  <nx-greeting [title]="title"></nx-greeting>
  <img
    width="450"
    src="https://raw.githubusercontent.com/nrwl/nx/master/nx-logo.png"
  />
</div>

<p>This is an Angular app built with <a href="https://nx.dev">Nx</a>.</p>
<p>🔎 **Nx is a set of Angular CLI power-ups for modern development.**</p>

<h2>Quick Start & Documentation</h2>

<ul>
  <li>
    <a href="https://nx.dev/getting-started/what-is-nx"
      >30-minute video showing all Nx features</a
    >
  </li>
  <li>
    <a href="https://nx.dev/tutorial/01-create-application"
      >Interactive tutorial</a
    >
  </li>
</ul>

<h2>Todos</h2>

<ul>
  <li *ngFor="let t of todos | async" class="todo">{{ t.title }}</li>
</ul>

<button id="add-todo" (click)="addTodo()">Add Todo</button>

<router-outlet></router-outlet>
