// nx/apps/reactapp/src/app/app.tsx
import './app.scss';

import { ToDo, ToDoGroupId, ToDoGroups, ToDoGroup } from '@nx/data';
import { uuid } from '@nx/utils';
import React from 'react';
import { BrowserRouter as Router } from 'react-router-dom';

import ToDoGroupComponent from './components/to-do-group/to-do-group.component';

interface State {
  groups: ToDoGroups;
}
export class App extends React.Component<{}, State> {
  readonly backendUrl = 'http://localhost:3333';
  constructor(props: {}) {
    super(props);

    this.onAddTask = this.onAddTask.bind(this);
    this.onTaskChange = this.onTaskChange.bind(this);
  }

  componentDidMount(): void {
    this.loadToDoGroups();
  }

  async loadToDoGroups(): Promise<void> {
    const response = await fetch(this.backendUrl + '/api/todos');
    const groups = await response.json();
    this.setState({ groups });
  }

  onAddTask(task: ToDo): void {
    fetch(this.backendUrl + '/api/addToDo', {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify(task)
    }).then(() => this.loadToDoGroups());
  }

  onTaskChange(task: ToDo): void {
    fetch(this.backendUrl + '/api/todo', {
      method: 'PUT',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify(task)
    }).then(() => this.loadToDoGroups());
  }

  render(): any {
    return (
      <Router>
        <eisenhower-matrix-header />
        <div className="matrix">
          <div className="matrix__column" />
          <div className="matrix__column">
            <h2>Urgent</h2>
          </div>
          <div className="matrix__column">
            <h2>Less urgent</h2>
          </div>
          <div className="matrix__column matrix__column--vertical">
            <h2>Important</h2>
          </div>
          <ToDoGroupComponent
            group={
              this.state &&
              this.state.groups &&
              this.state.groups[ToDoGroupId.do]
            }
            onAddTask={this.onAddTask}
            onTaskDoneChange={this.onTaskChange}
            id="do"
          />
          <ToDoGroupComponent
            group={
              this.state &&
              this.state.groups &&
              this.state.groups[ToDoGroupId.schedule]
            }
            onAddTask={this.onAddTask}
            onTaskDoneChange={this.onTaskChange}
            id="schedule"
          />
          <div className="matrix__column matrix__column--vertical">
            <h2>Less Important</h2>
          </div>
          <ToDoGroupComponent
            group={
              this.state &&
              this.state.groups &&
              this.state.groups[ToDoGroupId.delegate]
            }
            onAddTask={this.onAddTask}
            onTaskDoneChange={this.onTaskChange}
            id="delegate"
          />
          <ToDoGroupComponent
            group={
              this.state &&
              this.state.groups &&
              this.state.groups[ToDoGroupId.elimminate]
            }
            onAddTask={this.onAddTask}
            onTaskDoneChange={this.onTaskChange}
            id="eliminate"
          />
        </div>
      </Router>
    );
  }
}

export default App;

// nx/apps/ionic/src/app/app.component.ts
import { Component } from '@angular/core';

import { Platform } from '@ionic/angular';
import { SplashScreen } from '@ionic-native/splash-screen/ngx';
import { StatusBar } from '@ionic-native/status-bar/ngx';
import { uuid } from '@nx/utils';
import { HttpClient, HttpResponse } from '@angular/common/http';
import { switchMap } from 'rxjs/operators';
import { ToDoGroups, ToDo, ToDoGroupId } from '@nx/data';

@Component({
  selector: 'app-root',
  templateUrl: 'app.component.html',
  styleUrls: ['./app.component.scss']
})
export class AppComponent {
  readonly backendUrl = 'http://xxx';
  groups: ToDoGroups;
  ToDoGroupId = ToDoGroupId;

  constructor(
    private http: HttpClient,
    private platform: Platform,
    private splashScreen: SplashScreen,
    private statusBar: StatusBar
  ) {
    this.initializeApp();
    this.loadToDoGroups();
  }

  initializeApp() {
    this.platform.ready().then(() => {
      this.statusBar.styleDefault();
      this.splashScreen.hide();
    });
  }

  async loadToDoGroups(): Promise<void> {
    const response = this.http
      .get(this.backendUrl + '/api/todos')
      .subscribe((res: ToDoGroups) => {this.groups = res});
  }

  onAddTask(task: ToDo): void {
    this.http
      .post(this.backendUrl + '/api/addToDo', task)
      .subscribe(() => this.loadToDoGroups());
  }

  onTaskChange(task: ToDo): void {
    this.http
      .put(this.backendUrl + '/api/todo', task)
      .subscribe(() => this.loadToDoGroups());
  }
}

<ion-app>
  <ion-content>
    <eisenhower-matrix-header></eisenhower-matrix-header>
    <nx-to-do-groups
      *ngIf="!!groups"
      [doGroup]="groups[ToDoGroupId.do]"
      [scheduleGroup]="groups[ToDoGroupId.schedule]"
      [delegateGroup]="groups[ToDoGroupId.delegate]"
      [eliminateGroup]="groups[ToDoGroupId.elimminate]"
      (addToDo)="onAddTask($event)"
      (updateToDo)="onTaskChange($event)"
    ></nx-to-do-groups>
  </ion-content>
</ion-app>
