// nx/apps/reactapp/src/app/components/to-do-group/to-do-group.component.tsx
import './to-do-group.component.scss';

import { ToDo, ToDoGroup, ToDoGroupId } from '@nx/data';
import React from 'react';
import { MdAlarmOn, MdEvent, MdRemoveCircleOutline, MdPersonAdd } from 'react-icons/md';

import TaskComponent from '../task/task.component';
import { uuid } from '@nx/utils';

interface Props {
  id: string;
  group: ToDoGroup;
  onTaskDoneChange: (task: ToDo) => void;
  onAddTask: (task: ToDo) => void;
}
export default class ToDoGroupComponent extends React.Component<Props, {}> {
  inputRef: React.RefObject<HTMLInputElement>;
  constructor(props: Props) {
    super(props);

    this.inputRef = React.createRef();
    this.onTaskDoneChange = this.onTaskDoneChange.bind(this);
    this.onAddTask = this.onAddTask.bind(this);
  }
  onTaskDoneChange(task: ToDo): void {
    this.props.onTaskDoneChange(task);
  }
  onAddTask(e: React.KeyboardEvent<HTMLInputElement>): void {
    if (e.key === 'Enter') {
      this.props.onAddTask({
        id: uuid(),
        done: false,
        title: this.inputRef.current.value,
        group: this.props.group.id
      });
      this.inputRef.current.value = '';
    }
  }
  getIconJSX(): JSX.Element {
    switch (this.props.group.id) {
      case ToDoGroupId.do:
        return <MdAlarmOn />;
      case ToDoGroupId.schedule:
        return <MdEvent />;
      case ToDoGroupId.delegate:
        return <MdPersonAdd />;
      case ToDoGroupId.elimminate:
        return <MdRemoveCircleOutline />;
    }
  }
  render(): JSX.Element {
    return (
      <div id={this.props.id} className="to-do-group">
        <div className="to-do-group__content">
          <div className="to-do-group__title">
            <div className="to-do-group__title__wrapper">
              <div className="to-do-group__icon">
                {this.props.group && this.getIconJSX()}
              </div>
              <h2>{this.props.group && this.props.group.title}</h2>
            </div>
          </div>
          <div className="to-do-group__list-wrapper">
            <div className="to-do-group__list">
              <ul>
                {this.props.group &&
                  this.props.group.toDo.map((task: ToDo) => (
                    <TaskComponent
                      key={task.id}
                      task={task}
                      onTaskDoneChange={this.onTaskDoneChange}
                    />
                  ))}
              </ul>
            </div>
          </div>
          <div className="to-do-group__add-new-task">
            <span>+</span>
            <input
              type="text"
              placeholder="New task"
              ref={this.inputRef}
              onKeyDown={this.onAddTask}
            />
          </div>
        </div>
      </div>
    );
  }
}

// nx/apps/angularapp/src/app/components/to-do-group/to-do-group.component.ts
import {
  Component,
  OnInit,
  ElementRef,
  ViewChild,
  Input,
  Output,
  EventEmitter
} from '@angular/core';
import { Observable } from 'rxjs';
import { ToDoGroup, ToDo, ToDoGroupId } from '@nx/data';
import { uuid } from '@nx/utils';
import { toDoQuery } from '../../+state/to-do.selectors';

@Component({
  selector: 'nx-to-do-group',
  templateUrl: './to-do-group.component.html',
  styleUrls: ['./to-do-group.component.scss']
})
export class ToDoGroupComponent {
  @ViewChild('addTaskInputElement', { static: true })
  addTaskInput: ElementRef<HTMLInputElement>;

  @Input()
  group: ToDoGroup | undefined;

  @Output()
  addToDo: EventEmitter<ToDo> = new EventEmitter<ToDo>();
  @Output()
  updateToDo = new EventEmitter<ToDo>();

  groupIds = ToDoGroupId;

  constructor() {}

  addTask(value: string): void {
    if (value) {
      this.addToDo.emit({
        id: uuid(),
        done: false,
        title: value,
        group: this.group.id
      });
      this.addTaskInput.nativeElement.value = '';
    }
  }

  onUpdateToDo(event: ToDo): void {
    this.updateToDo.emit(event);
  }

  trackToDoBy(index: number, toDo: ToDo): string {
    return toDo.id;
  }
}

<div class="to-do-group">
  <div class="to-do-group__content">
    <div *ngIf="group" class="to-do-group__title">
      <div class="to-do-group__title__wrapper">
        <div class="to-do-group__icon" [ngSwitch]="group.id">
          <i class="material-icons" *ngSwitchCase="groupIds.do">alarm_on</i>
          <i class="material-icons" *ngSwitchCase="groupIds.schedule"
            >calendar_today</i
          >
          <i class="material-icons" *ngSwitchCase="groupIds.delegate"
            >how_to_reg</i
          >
          <i class="material-icons" *ngSwitchCase="groupIds.elimminate"
            >remove_circle_outline</i
          >
        </div>
        <h2>{{ group.title }}</h2>
      </div>
    </div>
    <div class="to-do-group__list-wrapper">
      <div class="to-do-group__list">
        <ul>
          <nx-task
            *ngFor="let t of group?.toDo; trackToDoBy"
            [task]="t"
            (doTask)="onUpdateToDo($event)"
          >
          </nx-task>
        </ul>
      </div>
    </div>
    <div class="to-do-group__add-new-task">
      <span>+</span>
      <input
        #addTaskInputElement
        (keyup.enter)="addTask(addTaskInputElement.value)"
        type="text"
        placeholder="New task"
      />
    </div>
  </div>
</div>
